### ISSUE TITLE
instructions not the most clear

### ISSUE THREAD

**Issue by velamyGH** [msikma/Easy3DS#1]
so im trying to build [this](https://github.com/cmaster25/Oneshot-For-3DS) game as a standalone cia file, the main problems i am having is figuring out what to do with bannertool.exe, 3dstool.exe and makerom.exe, as well as how to run the "./build.py games" script as listed in the readme. 

any help would be appreciated to know what to do with these :) sorry for the dumb questions, i always have trouble building these kinds of things

here is also a [drive upload](https://drive.google.com/drive/folders/1AKiUSlI7Ngk5ZZmPFgV3JhPvBQTbD0hT?usp=sharing) in case there is something else i have done wrong in my process

**Comment by msikma** [comment]
Hi there. I'll be honest: I've written this code very long ago and I haven't used it in a while. At some point, the 3DS version of EasyRPG broke so it became impossible to properly run games built with this script. (However I actually believe it was very recently fixed in [EasyRPG#2256](https://github.com/EasyRPG/Player/issues/2256), so hopefully that will not be a problem, although I haven't tested it.)

Basically you shouldn't have to do anything with bannertool/3dstool/etc. This script should do it for you. Unfortunately I don't use Windows, so I have not been able to actually test this properly for it. I'm fairly sure the script needs an adjustment for Windows (the binaries being executed in `make_cia_file()` should have `.exe` in the filename). That might be why it doesn't work. Let me know if you're unable to do this yourself and I'll give it a shot.

From your Drive upload I can see you still need to do the work explained in the "Preparing assets" section in the readme, though. It should be simple.

By the way, just in case, I want you to know that this isn't the EasyRPG repo. This is just a script I wrote to make it easier to build EasyRPG games for 3DS. You could also just install EasyRPG for 3DS itself and then run the game from there.

**Comment by velamyGH** [comment]
hi again :) 

so i now realized i misunderstood a part of the preparing assets section, assuming you had to replace the default files with what we wanted the banner and icon to be as you can see in my drive link. ive put the assets in the right place, but still cannot figure out how to make the build script execute properly, even after putting ".exe" at the end of the binaries in the .py script, im very bad at anything related to coding so any help from here would be appreciated

also yes im aware that the game im trying to build can be run from the standalone easyrpg app, ive been doing this the way listed in [the instructions](https://github.com/cmaster25/Oneshot-For-3DS) as a band-aid fix but i would much prefer to have the game run straight from a cia file as its the only game i actually play with easyrpg this way, plus love the idea of having oneshot as a game on my home screen :) let me know if theres anything else i can provide from my situation!!

**Comment by msikma** [comment]
I'll see if I can help you get the script running. Could you post what the output of the script is when running it?

**Comment by velamyGH** [comment]
this is what it outputs, i managed to make more progress on my laptop but cant seem to get past this part 
![image](https://user-images.githubusercontent.com/48131627/173656126-4b750448-926b-4dd7-8212-47709927e799.png)
![image](https://user-images.githubusercontent.com/48131627/173656171-7d44fcdf-4df8-42b0-8f6b-b482b7d13515.png)

**Comment by msikma** [comment]
Can you try it with `build.py -V games`? That should give some more information.

**Comment by velamyGH** [comment]
doing that gives the same output

**Comment by msikma** [comment]
I'll just go and have a look at it myself soon! Clearly the script needs to be fixed, and I haven't actually used it in a long time due to the 3DS build of EasyRPG breaking.

**Comment by velamyGH** [comment]
no worries, thanks for helping out!!

**Comment by velamyGH** [comment]
small update but trying again on my pc gives a completely different error that i still havent been able to fix 
![image](https://user-images.githubusercontent.com/48131627/174212507-6ce36680-2783-4e62-b70d-3d5c899cbb5b.png)

**Comment by msikma** [comment]
Could you see if this build works?

https://drive.google.com/file/d/1zFO0-fEbFICTHYtGVA3_UcFwnHipJ7Fu/view?usp=sharing

Note, this is just a test. It uses a *very* old build of EasyRPG. I'm going to take down this download later. I'm just trying to see if my script produces a working CIA as-is.

> small update but trying again on my pc gives a completely different error that i still havent been able to fix

This seems to indicate it maybe can't find the prerequisite programs such as makebanner.exe, etc. Can you try running makebanner.exe in that directory to see if it's accessible? I see you're running it in a different directory, so that might be a cause.

**Comment by msikma** [comment]
By the way, I might just do a rewrite of this script at some point. It's a typical script that was supposed to be very simple but then turned out to be a bit too complex, and now I feel like it's better off being structured differently. But in my current version of the script (I've got a few modifications that haven't been committed yet) it at least seems to work on my computer, so I'm sure getting it to work for you shouldn't be that difficult.

edit: relevant, linking this here so I don't forget about it: https://community.easyrpg.org/t/easyrpg-elf-file-for-3ds/1112

**Comment by velamyGH** [comment]
sorry for the late response, downloading the cia file and trying to open it gives this output when i try to launch:

An error occured (ErrDisp)

Error type: generic

Process id: 15
Process name: menu
Process title id: 0x0004003000008f02

Address: 0x0022939c
Error code: 0xc8804478

**Comment by velamyGH** [comment]
as for how to use makebanner, im not really sure what it is at all. but im guessing its part of bannertool but as for how to run anything related to that i have no idea

**Comment by Elekktrouus** [comment]
I don't mean to bump an old discussion but I'm wondering if this script still functions?
Bannertool also doesn't work for me (unrelated)

**Comment by msikma** [comment]
> I don't mean to bump an old discussion but I'm wondering if this script still functions?
> Bannertool also doesn't work for me (unrelated)

Unfortunately I haven't actually worked on this script for a long time. At one point the EasyRPG binary for 3DS broke and I haven't given it much thought since then. 

I think it probably doesn't work correctly on Windows as-is. I'll investigate this in the coming days though and see if I can make it work.

**Comment by velamyGH** [comment]
heya, any updates on this? still rly lookin forward to seeing this working in some way

**Comment by cdkk-git** [comment]
Hi there! I apologize for the very late reply. I found that this script was challenging to use, but I finally got it done. I do have a compiled CIA for Oneshot that I was able to do. You are welcome to try it, and more than welcome to download it and add it to this feed. [Download CIA](https://www.dropbox.com/scl/fi/2s3za2d5g0on7hdtjnn56/Oneshot-3DS.cia?rlkey=b8to1kab3o3s20bab4q1zbms0&dl=0)

**Comment by rrraya81** [comment]
made an account to ask:
how did you do it?

**Comment by Hobette** [comment]
hi, i too would like to know what changes you made to the code, if possible

**Comment by JupiterDoomsday** [comment]
So I managed to figure out that if makebanner is throwing an error, your icon.png or banner.png files are likely causing the error and may not be the right size. 
the banner size should be : 256 x 128
and the Icon size should be 48 x 48

I fixed my icon to 48x48 and that seemed to resolve the error I had with  makebanner

I am encountering Error 5: where makerom isn't working/ compiling the converted files
![Screenshot (50)](https://github.com/msikma/Easy3DS/assets/22850140/46889991-8367-41ac-80dc-5eabd380da6a)

**Comment by TheFlowersSystem** [comment]
getting the same "build failed at step 5 (makerom)" error too, so advice on getting past it would be helpful, 

figured it out. for me the issue was the CIA ID, i tried a bunch till the error stopped and the cia got made "004015" is a working ID if you get the step 5 error!

**Comment by Spoobunk** [comment]
Hey, if anyone is stumbling across this later on, I went through this process and eventually got a .cia. 
Like other people have mentioned, the banner and icon images have to be the correct sizes (256x128 and 48x48 respectively), otherwise bannertool will fail. 
Also, the provided cia id must start with 0 (or at least that's what worked for me), or else the id provided to makerom will be out of range, and it'll fail. 

Doing that got me a cia file, but unfortunately I can't tell if the game will run since it seems like easyRPG in general is having problems on my 3ds.
Also, there's [this script](https://github.com/EasyRPG/Player/tree/master/resources/3ds/cia_builder) which seems like a more streamlined alternative to this one.

Hope this is helpful

**Comment by DiplacusisAlt** [comment]
> so im trying to build [this](https://github.com/cmaster25/Oneshot-For-3DS) game as a standalone cia file, the main problems i am having is figuring out what to do with bannertool.exe, 3dstool.exe and makerom.exe, as well as how to run the "./build.py games" script as listed in the readme.
> 
> any help would be appreciated to know what to do with these :) sorry for the dumb questions, i always have trouble building these kinds of things
> 
> here is also a [drive upload](https://drive.google.com/drive/folders/1AKiUSlI7Ngk5ZZmPFgV3JhPvBQTbD0hT?usp=sharing) in case there is something else i have done wrong in my process

Been trying to crack this for the last couple of hours -- I got past one issue by downloading setuptools (b/c it was asking for a "distutils"), but now there's another issue. When I run "python build.py," it says, "The following arguments are required: dir"

<img width="870" height="40" alt="Image" src="https://github.com/user-attachments/assets/9499f1ec-5765-4396-ac19-ba521662b993" />

I haven't touched the code in any great capacity, so I'm pretty lost. Could it be an issue with setuptools itself? Should I downgrade to an earlier edition of Python somehow? It says the same thing when I run it in Powershell. And when I instead type "./build.py" into it, the program closes immediately afterward, even after I tried adding "input()" to the end of build.py! I'm pretty confused here.

Also, about the script that Spoobunk found, when I tried it myself (adding the game folder to the romfs folder, etc), the resulting .cia merely brought me into the EasyRPG menu. Does it work properly if I have the actual game in my 3DS proper, though?

**Comment by OmoriDemakeDev** [comment]
> Been trying to crack this for the last couple of hours -- I got past one issue by downloading setuptools (b/c it was asking for a "distutils"), but now there's another issue. When I run "python build.py," it says, "The following arguments are required: dir"

> I haven't touched the code in any great capacity, so I'm pretty lost. Could it be an issue with setuptools itself? Should I downgrade to an earlier edition of Python somehow? It says the same thing when I run it in Powershell. And when I instead type "./build.py" into it, the program closes immediately afterward, even after I tried adding "input()" to the end of build.py! I'm pretty confused here.

Hi, I've been having the exact same issue. I also downloaded setuptools to get the exact same error. Did you ever find a fix? If not, what error does it give you when you type `./build.py -V games` into the command prompt? Here is what I get:

![Image](https://github.com/user-attachments/assets/d129a5a2-f3b2-4f7c-bad8-9e4a0eadc653)

First Edit (10/29/25):
I pulled an all-nighter and here is what I discovered through countless Google searches, guessing and checking. @Spoobunk is right on the money with their link to [a more effective cia builder](https://github.com/EasyRPG/Player/tree/master/resources/3ds/cia_builder). However, I'm thinking it might not be impossible to salvage this one. As @DiplacusisAlt mentioned, setuptools is a double-edged sword, fixing one problem and adding another. In my more detailed error diagnosis listed above, there are two listed issues. One being that all instances of `find_executable` must be replaced, the other being that the script thinks the game uses default assets, even when it doesn't (or so I thought). I believe I've fixed both of these problems.

Let's start with the latter. My command prompt kept insisting that my assets were identical to the default assets, even though I was sure I had changed them. @velamyGH had a similar problem, and thanks to them making their [drive upload](https://drive.google.com/drive/folders/1AKiUSlI7Ngk5ZZmPFgV3JhPvBQTbD0hT?usp=sharing) open for all of us to look at (HUGE thanks for that, it was super helpful!) I identified what was going on. You're supposed to make a folder in the game directory called "3DS" and put the altered assets (icon, banner, audio and cfg file) in there. While I knew that from the beginning, what I DIDN'T know was that the assets in the _Easy3DS-master\assets\defaults_ directory are supposed to STAY DEFAULT. For some reason, I thought that those were supposed to be customized too. But when I customized it to be the same as the assets in my game folder, the script used the default folder as a reference for what default was. Therefore, even though all files were original, it thought they weren't changed.

**Paragraph TL;DR:** Copy the stuff from _Easy3DS-master\assets\defaults_ to a new folder called "3DS" in the _Easy3DS-master\games\game-title-example_ directory and change it there, but LEAVE THE DEFAULT FOLDER'S CONTENTS UNCHANGED.

Alright, next issue. Replacing `find_executable` instances. To do this, I right clicked the build.py file so I could choose where to open it from. Instead of Python, I opened it in Notepad. Lines 13 and 14 immediately stood out to me as a problem:

```
from distutils.dir_util import copy_tree
from distutils.spawn import find_executable
```

I replaced these lines with this:

```
from shutil import copytree
from shutil import which
```

Line 404 was also a problem:

`return find_executable(name) is not None`

I replaced it with this:

`return which(name) is not None`

You may be asking yourself, what does this do for us? I've no clue, I just googled stuff and guessing worked eventually.

So after I figured all of that out, I ran `./build.py games` with my fingers crossed, only to get this:

<img width="623" height="58" alt="Image" src="https://github.com/user-attachments/assets/22f3f936-b317-493a-b233-f599d8d1c0aa" />

I was a bit dissapointed, but was hoping that @msikma's `./build.py -V games` line would get Command Prompt to spit out a more detailed explanation of what went wrong. But all I got from it was this:

<img width="1063" height="91" alt="Image" src="https://github.com/user-attachments/assets/5c64805c-a15f-496f-afac-220e58f865a8" />

Dead end. No more clues.

I am officially on the verge of collapsing in exhaustion and losing my mind. But I hope that this info will find the right people (if anyone even cares anymore) and they can get something out of this. I will be using the [secondary option](https://github.com/EasyRPG/Player/tree/master/resources/3ds/cia_builder) for converting my RPG Maker 2003 files to cia, but on the side I think I'll keep at trying to get this one to work because I can tell a lot of work was put into it and seeing it in it's prime again would be glorious. That's all for now, I'll make more edits if I find anything else.
